# @name index
GET http://localhost:3000 HTTP/1.1

###

# @name post-completions
POST http://localhost:3000/completions HTTP/1.1
Content-Type: application/json

{
  "videoId": "ae988b7d-d4bb-4846-a26d-6ab860b97589",
  "prompt": "Generate a summary from video transcription informed as follows: '''{transcription}'''",
  "temperature": 0.2
}

###

# @name get-prompts
GET http://localhost:3000/prompts HTTP/1.1

###

# @name post-transcriptions
POST http://localhost:3000/transcriptions/ae988b7d-d4bb-4846-a26d-6ab860b97589 HTTP/1.1
Content-Type: application/json

{
  "prompt": "typescript,javascript,nodejs,node,js,ts"
}

###

# @name post-videos
POST http://localhost:3000/videos HTTP/1.1
Content-Type: multipart/form-data; boundary=----PostVideoBody

------PostVideoBody
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------PostVideoBody--
